name: Continuous Integration
on:
  workflow_dispatch: {}
  # schedule:
    # Weekly every Saturday at midnight
    # - cron: '0 0 * * 6'

jobs:
  test-lint-scan:
    uses: ./.github/workflows/test_lint_scan.yml

  collision-test:
    runs-on:
      - self-hosted
      - macos-local

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pdm install -dG test
      - name: Run Testing
        run: |
          pdm run -v testing-slow
