name: Continuous Integration
on:
  workflow_dispatch: {}
  schedule:
    # Weekly every Saturday at midnight
    - cron: '0 0 * * 6'

jobs:
  test-lint-scan:
    uses: ./.github/workflows/test_lint_scan.yml

  collision-test:
    runs-on:
      - self-hosted
      - macos-local

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Set up uv
        uses: astral-sh/setup-uv@v9.0.0
      - name: Install dependencies
        run: |
          uv sync --group test
      - name: Run Testing
        run: |
          uv run -v pytest local/tests --runslow
