name: Continuous Integration
on:
  workflow_dispatch: {}
  schedule:
    # Weekly every Saturday at midnight
    - cron: '0 0 * * 6'

jobs:
  test-lint-scan:
    uses: ./.github/workflows/test_lint_scan.yml

  collision-test:
    runs-on:
      - self-hosted
      - macos-local

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - name: Install dependencies
        run: |
          uv sync --group test
      - name: Run Testing
        run: |
          uv run -v pytest local/tests --runslow
