name: Test - Lint - Scan
on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, "3.10", 3.11, 3.12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0 # v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pdm install -dG :all
      - name: Run Testing
        run: |
          pdm run -v testing

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0 # v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pdm install -dG :all --no-self
      - name: Run Linting
        run: |
          pdm run -v lint-full

  scan:
    name: Scanning
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0 # v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pdm install -dG :all --no-self
      - name: Initialize Runtime Code Analysis
        uses: github/codeql-action/init@0daab03d71ff584ef619d027a3fd9146679c5d84 # v3
        with:
          languages: python
      - name: Perform Runtime Code Analysis
        uses: github/codeql-action/analyze@0daab03d71ff584ef619d027a3fd9146679c5d84 # v3
        env:
          CODEQL_EXTRACTOR_PYTHON_ANALYSIS_VERSION: 3.12
      - name: Perform Secure Code Analysis (Secrets)
        uses: trufflesecurity/trufflehog@ab5dd03ee012e5f372e2ba82c4813c2ba1331261 # main
