name: Test - Lint - Scan
on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  test:
    name: Testing
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", 3.11, 3.12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync --group test
      - name: Run Testing
        run: |
          uv run -v pytest local/tests

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          uv sync --group tox
      - name: Run Linting
        run: |
          uv run -v tox r -e check

  scan:
    name: Scanning
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          uv sync --all-groups --no-install-project
      - name: Initialize Runtime Code Analysis
        uses: github/codeql-action/init@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          languages: python
      - name: Perform Runtime Code Analysis
        uses: github/codeql-action/analyze@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        env:
          CODEQL_EXTRACTOR_PYTHON_ANALYSIS_VERSION: 3.12
      - name: Perform Secure Code Analysis (Secrets)
        uses: trufflesecurity/trufflehog@bc3a3ae6e097580bdef61492c78f79a4651319df # main
